concepts:
  pedestrian: pedestrian
  motorcycle: motorcycle
  bicycle: bicycle
  electric scooter: electric scooter
  car: car
  bus: bus
  truck: truck
  traffic light: vehicle traffic light #aunque no se vea la luz
  traffic sign: visible traffic signs #se debe ver el cartel por delante
  rider: rider
  crosswalk: crosswalk